### ISSUE TITLE
Error: logger not found when using the stash "tag" task in the plugin

### ISSUE THREAD

**Issue by mzieger** [xebialabs-community/xlr-bitbucket-plugin#9]

**Comment by mzieger** [comment]
This is the issue: logger is not initialized
def stash_tagrelease(self, variables):
        endpoint = "/rest/git/1.0/projects/%s/repos/%s/tags" % (variables['project'], variables['repository'])
        **logger.warn("Tag project (%s/%s" % (variables['project'], variables['repository']))**
        content = '''{"force":"true", "message":"%s", "name":"%s", "startPoint":"refs/heads/%s", "type":"ANNOTATED"}''' % (variables['message'], variables['tagname'], variables['branch'])
        response = self.api_call('POST', endpoint, body=content, contentType="application/json")
        data = response.getResponse()
        return {'output': data}

**Comment by jgifford25** [comment]
In addition to that line, the endpoint right before it has a bad URL path.  According to Atlassian's documentation on this, it should be'/rest/api/1.0/projects/%s/repos/%s/tags' instead ('git' --> 'api'): https://docs.atlassian.com/DAC/rest/stash/3.11.6/stash-rest.html#idp2494976

With our testing, we also found startPoint in the json will be another issue.  Sometime between the product name change (Stash --> Bitbucket Server), this value should now be a Commit Hash, not a repo path.  During our testing, Bitbucket Server was happy enough to return a 200 even though the tag was not created.  We're using Bitbucket Server 5.10.0 and I think anything newer will also have this problem.

**Comment by ndebuhr** [comment]
Thanks @mzieger @jgifford25 
https://github.com/xebialabs-community/xlr-bitbucket-plugin/pull/12
The /api/git/ api endpoint is valid https://docs.atlassian.com/bitbucket-server/rest/5.10.0/bitbucket-git-rest.html#idm303783242944, but for consistency I agree the /api/rest/ should be used https://docs.atlassian.com/bitbucket-server/rest/5.10.0/bitbucket-rest.html#idm532023645760
